import { Item } from "../../interfaces";

export class Effect {
    items: Item[] = [
        {"id":1,"label":"A\u00e7\u00e3o em Movimento","max":1,"min":1,"checked":false,"points":1},
        {"id":70,"label":"Adapta\u00e7\u00e3o ao Ambiente","max":1,"min":1,"checked":false,"points":1},
        {"id":2,"label":"Agarrar Aprimorado","max":1,"min":1,"checked":false,"points":1},
        {"id":3,"label":"Agarrar Instant\u00e2neo","max":1,"min":1,"checked":false,"points":1},
        {"id":4,"label":"Agarrar Preciso","max":1,"min":1,"checked":false,"points":1},
        {"id":5,"label":"Alvo Esquivo","max":1,"min":1,"checked":false,"points":1},
        {"id":71,"label":"Ambidestria","max":1,"min":1,"checked":false,"points":1},
        {"id":6,"label":"Ambiente Favorito","max":0,"min":1,"checked":false,"points":1},
        {"id":7,"label":"Arma\u00e7\u00e3o","max":1,"min":1,"checked":false,"points":1},
        {"id":8,"label":"Arremessar Aprimorado","max":1,"min":1,"checked":false,"points":1},
        {"id":46,"label":"Art\u00edfice","max":1,"min":1,"checked":false,"points":1},
        {"id":47,"label":"Assustar","max":1,"min":1,"checked":false,"points":1},
        {"id":9,"label":"Ataque Acurado","max":1,"min":1,"checked":false,"points":1},
        {"id":10,"label":"Ataque Atordoante","max":1,"min":1,"checked":false,"points":1},
        {"id":11,"label":"Ataque Defensivo","max":1,"min":1,"checked":false,"points":1},
        {"id":12,"label":"Ataque Domin\u00f3","max":2,"min":1,"checked":false,"points":1},
        {"id":13,"label":"Ataque Furtivo","max":4,"min":1,"checked":false,"points":1},
        {"id":14,"label":"Ataque Imprudente","max":1,"min":1,"checked":false,"points":1},
        {"id":15,"label":"Ataque Poderoso","max":1,"min":1,"checked":false,"points":1},
        {"id":48,"label":"Atraente","max":0,"min":1,"checked":false,"points":1},
        {"id":16,"label":"Atropelar Aprimorado","max":1,"min":1,"checked":false,"points":1},
        {"id":17,"label":"Atropelar R\u00e1pido","max":1,"min":1,"checked":false,"points":1},
        {"id":72,"label":"Avalia\u00e7\u00e3o","max":1,"min":1,"checked":false,"points":1},
        {"id":49,"label":"Bem Informado","max":1,"min":1,"checked":false,"points":1},
        {"id":50,"label":"Bem Relacionado","max":1,"min":1,"checked":false,"points":1},
        {"id":73,"label":"Benef\u00edcio","max":0,"min":1,"checked":false,"points":1},
        {"id":51,"label":"Blefe Acrob\u00e1tico","max":1,"min":1,"checked":false,"points":1},
        {"id":18,"label":"Bloquear Aprimorado","max":0,"min":1,"checked":false,"points":1},
        {"id":74,"label":"Capangas","max":0,"min":1,"checked":false,"points":1},
        {"id":52,"label":"Contatos","max":1,"min":1,"checked":false,"points":1},
        {"id":19,"label":"Cr\u00edtico Aprimorado","max":0,"min":1,"checked":false,"points":1},
        {"id":75,"label":"De P\u00e9","max":1,"min":1,"checked":false,"points":1},
        {"id":20,"label":"Defesa Aprimorada","max":2,"min":1,"checked":false,"points":1},
        {"id":21,"label":"Derrubar Aprimorado","max":1,"min":1,"checked":false,"points":1},
        {"id":22,"label":"Desarmar Aprimorado","max":0,"min":1,"checked":false,"points":1},
        {"id":53,"label":"Distrair","max":2,"min":1,"checked":false,"points":1},
        {"id":76,"label":"Duro de Matar","max":1,"min":1,"checked":false,"points":1},
        {"id":54,"label":"Empatia com Animais","max":1,"min":1,"checked":false,"points":1},
        {"id":77,"label":"Equipamento","max":0,"min":1,"checked":false,"points":1},
        {"id":55,"label":"Esconder-se \u00e0 Plena Vista","max":1,"min":1,"checked":false,"points":1},
        {"id":64,"label":"Esfor\u00e7o Supremo","max":0,"min":1,"checked":false,"points":1},
        {"id":23,"label":"Especializa\u00e7\u00e3o em Ataque","max":0,"min":1,"checked":false,"points":1},
        {"id":24,"label":"Esquiva Fabulosa","max":0,"min":1,"checked":false,"points":1},
        {"id":25,"label":"Estrangular","max":1,"min":1,"checked":false,"points":1},
        {"id":26,"label":"Evas\u00e3o","max":2,"min":1,"checked":false,"points":1},
        {"id":56,"label":"Fascinar","max":4,"min":1,"checked":false,"points":1},
        {"id":57,"label":"Faz-Tudo","max":1,"min":1,"checked":false,"points":1},
        {"id":58,"label":"Ferramentas Improvisadas","max":1,"min":1,"checked":false,"points":1},
        {"id":27,"label":"Foco em Ataque","max":0,"min":1,"checked":false,"points":1},
        {"id":28,"label":"Foco em Esquiva","max":0,"min":1,"checked":false,"points":1},
        {"id":29,"label":"F\u00faria","max":0,"min":1,"checked":false,"points":1},
        {"id":30,"label":"Golpe Cr\u00edtico","max":1,"min":1,"checked":false,"points":1},
        {"id":31,"label":"Imobilizar Aprimorado","max":1,"min":1,"checked":false,"points":1},
        {"id":32,"label":"Iniciativa Aprimorada","max":0,"min":1,"checked":false,"points":1},
        {"id":65,"label":"Inspirar","max":5,"min":1,"checked":false,"points":1},
        {"id":78,"label":"Interpor-se","max":1,"min":1,"checked":false,"points":1},
        {"id":59,"label":"Inventor","max":1,"min":1,"checked":false,"points":1},
        {"id":66,"label":"Lideran\u00e7a","max":1,"min":1,"checked":false,"points":1},
        {"id":33,"label":"Luta Cega","max":1,"min":1,"checked":false,"points":1},
        {"id":34,"label":"Luta no Ch\u00e3o","max":1,"min":1,"checked":false,"points":1},
        {"id":35,"label":"Maestria em Arremesso","max":0,"min":1,"checked":false,"points":1},
        {"id":60,"label":"Maestria em Per\u00edcia","max":0,"min":1,"checked":false,"points":1},
        {"id":79,"label":"Mem\u00f3ria Eid\u00e9tica","max":1,"min":1,"checked":false,"points":1},
        {"id":36,"label":"Mira Aprimorada","max":1,"min":1,"checked":false,"points":1},
        {"id":80,"label":"Mudan\u00e7a R\u00e1pida","max":2,"min":1,"checked":false,"points":1},
        {"id":37,"label":"Oponente Favorito","max":0,"min":1,"checked":false,"points":1},
        {"id":81,"label":"Parceiro","max":0,"min":1,"checked":false,"points":1},
        {"id":82,"label":"Plano Genial","max":1,"min":1,"checked":false,"points":1},
        {"id":38,"label":"Prender \u00e0 Dist\u00e2ncia","max":1,"min":1,"checked":false,"points":1},
        {"id":39,"label":"Prender Arma","max":1,"min":1,"checked":false,"points":1},
        {"id":83,"label":"Presen\u00e7a Aterradora","max":0,"min":1,"checked":false,"points":1},
        {"id":40,"label":"Quebrar Aprimorado","max":1,"min":1,"checked":false,"points":1},
        {"id":41,"label":"Quebrar Arma","max":1,"min":1,"checked":false,"points":1},
        {"id":61,"label":"Rastrear","max":1,"min":1,"checked":false,"points":1},
        {"id":42,"label":"Redirecionar","max":1,"min":1,"checked":false,"points":1},
        {"id":62,"label":"Ritualista","max":1,"min":1,"checked":false,"points":1},
        {"id":43,"label":"Rolamento Defensivo","max":0,"min":1,"checked":false,"points":1},
        {"id":44,"label":"Saque R\u00e1pido","max":2,"min":1,"checked":false,"points":1},
        {"id":84,"label":"Segunda Chance","max":0,"min":1,"checked":false,"points":1},
        {"id":85,"label":"Sem Medo","max":1,"min":1,"checked":false,"points":1},
        {"id":67,"label":"Sorte","max":0,"min":1,"checked":false,"points":1},
        {"id":68,"label":"Sorte de Principiante","max":1,"min":1,"checked":false,"points":1},
        {"id":45,"label":"Tiro Preciso","max":2,"min":1,"checked":false,"points":1},
        {"id":86,"label":"Toler\u00e2ncia","max":0,"min":1,"checked":false,"points":1},
        {"id":69,"label":"Tomar a Iniciativa","max":1,"min":1,"checked":false,"points":1},
        {"id":87,"label":"Trabalho em Equipe","max":3,"min":1,"checked":false,"points":1},
        {"id":88,"label":"Transe","max":1,"min":1,"checked":false,"points":1},
        {"id":63,"label":"Zombar","max":1,"min":1,"checked":false,"points":1},
    ];
}
