import { Item } from "../../interfaces";

export class Effect {
    items: Item[] = [
        {"id":1,"label":"A\u00e7\u00e3o em Movimento","min":1,"max":1, "checked":false, "points":1},
        {"id":2,"label":"Agarrar Aprimorado","min":1,"max":1, "checked":false, "points":1},
        {"id":3,"label":"Agarrar Instant\u00e2neo","min":1,"max":1, "checked":false, "points":1},
        {"id":4,"label":"Agarrar Preciso","min":1,"max":1, "checked":false, "points":1},
        {"id":5,"label":"Alvo Esquivo","min":1,"max":1, "checked":false, "points":1},
        {"id":6,"label":"Ambiente Favorito","min":1,"max":0, "checked":false, "points":1},
        {"id":7,"label":"Arma\u00e7\u00e3o","min":1,"max":1, "checked":false, "points":1},
        {"id":8,"label":"Arremessar Aprimorado","min":1,"max":1, "checked":false, "points":1},
        {"id":9,"label":"Ataque Acurado","min":1,"max":1, "checked":false, "points":1},
        {"id":10,"label":"Ataque Atordoante","min":1,"max":1, "checked":false, "points":1},
        {"id":11,"label":"Ataque Defensivo","min":1,"max":1, "checked":false, "points":1},
        {"id":12,"label":"Ataque Domin\u00f3","min":1,"max":2, "checked":false, "points":1},
        {"id":13,"label":"Ataque Furtivo","min":1,"max":4, "checked":false, "points":1},
        {"id":14,"label":"Ataque Imprudente","min":1,"max":1, "checked":false, "points":1},
        {"id":15,"label":"Ataque Poderoso","min":1,"max":1, "checked":false, "points":1},
        {"id":16,"label":"Atropelar Aprimorado","min":1,"max":1, "checked":false, "points":1},
        {"id":17,"label":"Atropelar R\u00e1pido","min":1,"max":1, "checked":false, "points":1},
        {"id":18,"label":"Bloquear Aprimorado","min":1,"max":0, "checked":false, "points":1},
        {"id":19,"label":"Cr\u00edtico Aprimorado","min":1,"max":0, "checked":false, "points":1},
        {"id":20,"label":"Defesa Aprimorada","min":1,"max":2, "checked":false, "points":1},
        {"id":21,"label":"Derrubar Aprimorado","min":1,"max":1, "checked":false, "points":1},
        {"id":22,"label":"Desarmar Aprimorado","min":1,"max":0, "checked":false, "points":1},
        {"id":23,"label":"Especializa\u00e7\u00e3o em Ataque","min":1,"max":0, "checked":false, "points":1},
        {"id":24,"label":"Esquiva Fabulosa","min":1,"max":0, "checked":false, "points":1},
        {"id":25,"label":"Estrangular","min":1,"max":1, "checked":false, "points":1},
        {"id":26,"label":"Evas\u00e3o","min":1,"max":2, "checked":false, "points":1},
        {"id":27,"label":"Foco em Ataque","min":1,"max":0, "checked":false, "points":1},
        {"id":28,"label":"Foco em Esquiva","min":1,"max":0, "checked":false, "points":1},
        {"id":29,"label":"F\u00faria","min":1,"max":0, "checked":false, "points":1},
        {"id":30,"label":"Golpe Cr\u00edtico","min":1,"max":1, "checked":false, "points":1},
        {"id":31,"label":"Imobilizar Aprimorado","min":1,"max":1, "checked":false, "points":1},
        {"id":32,"label":"Iniciativa Aprimorada","min":1,"max":0, "checked":false, "points":1},
        {"id":33,"label":"Luta Cega","min":1,"max":1, "checked":false, "points":1},
        {"id":34,"label":"Luta no Ch\u00e3o","min":1,"max":1, "checked":false, "points":1},
        {"id":35,"label":"Maestria em Arremesso","min":1,"max":0, "checked":false, "points":1},
        {"id":36,"label":"Mira Aprimorada","min":1,"max":1, "checked":false, "points":1},
        {"id":37,"label":"Oponente Favorito","min":1,"max":0, "checked":false, "points":1},
        {"id":38,"label":"Prender \u00e0 Dist\u00e2ncia","min":1,"max":1, "checked":false, "points":1},
        {"id":39,"label":"Prender Arma","min":1,"max":1, "checked":false, "points":1},
        {"id":40,"label":"Quebrar Aprimorado","min":1,"max":1, "checked":false, "points":1},
        {"id":41,"label":"Quebrar Arma","min":1,"max":1, "checked":false, "points":1},
        {"id":42,"label":"Redirecionar","min":1,"max":1, "checked":false, "points":1},
        {"id":43,"label":"Rolamento Defensivo","min":1,"max":0, "checked":false, "points":1},
        {"id":44,"label":"Saque R\u00e1pido","min":1,"max":2, "checked":false, "points":1},
        {"id":45,"label":"Tiro Preciso","min":1,"max":2, "checked":false, "points":1},
        {"id":46,"label":"Art\u00edfice","min":1,"max":1, "checked":false, "points":1},
        {"id":47,"label":"Assustar","min":1,"max":1, "checked":false, "points":1},
        {"id":48,"label":"Atraente","min":1,"max":0, "checked":false, "points":1},
        {"id":49,"label":"Bem Informado","min":1,"max":1, "checked":false, "points":1},
        {"id":50,"label":"Bem Relacionado","min":1,"max":1, "checked":false, "points":1},
        {"id":51,"label":"Blefe Acrob\u00e1tico","min":1,"max":1, "checked":false, "points":1},
        {"id":52,"label":"Contatos","min":1,"max":1, "checked":false, "points":1},
        {"id":53,"label":"Distrair","min":1,"max":2, "checked":false, "points":1},
        {"id":54,"label":"Empatia com Animais","min":1,"max":1, "checked":false, "points":1},
        {"id":55,"label":"Esconder-se \u00e0 Plena Vista","min":1,"max":1, "checked":false, "points":1},
        {"id":56,"label":"Fascinar","min":1,"max":4, "checked":false, "points":1},
        {"id":57,"label":"Faz-Tudo","min":1,"max":1, "checked":false, "points":1},
        {"id":58,"label":"Ferramentas Improvisadas","min":1,"max":1, "checked":false, "points":1},
        {"id":59,"label":"Inventor","min":1,"max":1, "checked":false, "points":1},
        {"id":60,"label":"Maestria em Per\u00edcia","min":1,"max":0, "checked":false, "points":1},
        {"id":61,"label":"Rastrear","min":1,"max":1, "checked":false, "points":1},
        {"id":62,"label":"Ritualista","min":1,"max":1, "checked":false, "points":1},
        {"id":63,"label":"Zombar","min":1,"max":1, "checked":false, "points":1},
        {"id":64,"label":"Esfor\u00e7o Supremo","min":1,"max":0, "checked":false, "points":1},
        {"id":65,"label":"Inspirar","min":1,"max":5, "checked":false, "points":1},
        {"id":66,"label":"Lideran\u00e7a","min":1,"max":1, "checked":false, "points":1},
        {"id":67,"label":"Sorte","min":1,"max":0, "checked":false, "points":1},
        {"id":68,"label":"Sorte de Principiante","min":1,"max":1, "checked":false, "points":1},
        {"id":69,"label":"Tomar a Iniciativa","min":1,"max":1, "checked":false, "points":1},
        {"id":70,"label":"Adapta\u00e7\u00e3o ao Ambiente","min":1,"max":1, "checked":false, "points":1},
        {"id":71,"label":"Ambidestria","min":1,"max":1, "checked":false, "points":1},
        {"id":72,"label":"Avalia\u00e7\u00e3o","min":1,"max":1, "checked":false, "points":1},
        {"id":73,"label":"Benef\u00edcio","min":1,"max":0, "checked":false, "points":1},
        {"id":74,"label":"Capangas","min":1,"max":0, "checked":false, "points":1},
        {"id":75,"label":"De P\u00e9","min":1,"max":1, "checked":false, "points":1},
        {"id":76,"label":"Duro de Matar","min":1,"max":1, "checked":false, "points":1},
        {"id":77,"label":"Equipamento","min":1,"max":0, "checked":false, "points":1},
        {"id":78,"label":"Interpor-se","min":1,"max":1, "checked":false, "points":1},
        {"id":79,"label":"Mem\u00f3ria Eid\u00e9tica","min":1,"max":1, "checked":false, "points":1},
        {"id":80,"label":"Mudan\u00e7a R\u00e1pida","min":1,"max":2, "checked":false, "points":1},
        {"id":81,"label":"Parceiro","min":1,"max":0, "checked":false, "points":1},
        {"id":82,"label":"Plano Genial","min":1,"max":1, "checked":false, "points":1},
        {"id":83,"label":"Presen\u00e7a Aterradora","min":1,"max":0, "checked":false, "points":1},
        {"id":84,"label":"Segunda Chance","min":1,"max":0, "checked":false, "points":1},
        {"id":85,"label":"Sem Medo","min":1,"max":1, "checked":false, "points":1},
        {"id":86,"label":"Toler\u00e2ncia","min":1,"max":0, "checked":false, "points":1},
        {"id":87,"label":"Trabalho em Equipe","min":1,"max":3, "checked":false, "points":1},
        {"id":88,"label":"Transe","min":1,"max":1, "checked":false, "points":1}
  ];
}
