export class newSkill {
    items: any[] = [
        {"id":1,"label":"Acrobacia","abilityKey":"destreza","min":1,"show":false,"points":1},
        {"id":2,"label":"Arte da Fulga","abilityKey":"destreza","min":1,"show":false,"points":1},
        {"id":3,"label":"Blefar","abilityKey":"carisma","min":1,"show":false,"points":1},
        {"id":4,"label":"Cavalgar","abilityKey":"destreza","min":1,"show":false,"points":1},
        {"id":5,"label":"Computadores","abilityKey":"inteligencia","min":1,"show":false,"points":1},
        {"id":6,"label":"Concentra\u00e7\u00e3o","abilityKey":"sabedoria","min":1,"show":false,"points":1},
        {"id":7,"label":"Conhecimento","abilityKey":"inteligencia","min":1,"show":false,"points":1},
        {"id":8,"label":"Desarmar Dispositivo","abilityKey":"inteligencia","min":1,"show":false,"points":1},
        {"id":9,"label":"Diplomacia","abilityKey":"carisma","min":1,"show":false,"points":1},
        {"id":10,"label":"Dirigir","abilityKey":"destreza","min":1,"show":false,"points":1},
        {"id":11,"label":"Disfarce","abilityKey":"carisma","min":1,"show":false,"points":1},
        {"id":12,"label":"Escalar","abilityKey":"forca","min":1,"show":false,"points":1},
        {"id":13,"label":"Furtividade","abilityKey":"destreza","min":1,"show":false,"points":1},
        {"id":14,"label":"Idiomas","abilityKey":"","min":1,"show":false,"points":1},
        {"id":15,"label":"Intimidar","abilityKey":"carisma","min":1,"show":false,"points":1},
        {"id":16,"label":"Intuir Inten\u00e7\u00e3o","abilityKey":"sabedoria","min":1,"show":false,"points":1},
        {"id":17,"label":"Investigar","abilityKey":"inteligencia","min":1,"show":false,"points":1},
        {"id":18,"label":"Lidar com Animais","abilityKey":"carisma","min":1,"show":false,"points":1},
        {"id":19,"label":"Medicina","abilityKey":"sabedoria","min":1,"show":false,"points":1},
        {"id":20,"label":"Nadar","abilityKey":"forca","min":1,"show":false,"points":1},
        {"id":21,"label":"Notar","abilityKey":"sabedoria","min":1,"show":false,"points":1},
        {"id":22,"label":"Obter Informa\u00e7\u00e3o","abilityKey":"carisma","min":1,"show":false,"points":1},
        {"id":23,"label":"Of\u00edcio","abilityKey":"inteligencia","min":1,"show":false,"points":1},
        {"id":24,"label":"Performance","abilityKey":"carisma","min":1,"show":false,"points":1},
        {"id":25,"label":"Pilotar","abilityKey":"destreza","min":1,"show":false,"points":1},
        {"id":26,"label":"Prestidigita\u00e7\u00e3o","abilityKey":"destreza","min":1,"show":false,"points":1},
        {"id":27,"label":"Procurar","abilityKey":"inteligencia","min":1,"show":false,"points":1},
        {"id":28,"label":"Profiss\u00e3o","abilityKey":"sabedoria","min":1,"show":false,"points":1},
        {"id":29,"label":"Sobreviv\u00eancia","abilityKey":"sabedoria"}
    ];
}